# Generated by Django 5.0.4 on 2024-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcode', models.CharField(max_length=5, verbose_name='код валюты')),
                ('date', models.DateField(max_length=100, verbose_name='дата')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='курс валюты')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюты',
            },
        ),
    ]
